const GET_ADDRESSES = 'GET_ADDRESSES';
const GET_ADDRESSES_REQUEST = 'GET_ADDRESSES_REQUEST';
const GET_ADDRESSES_SUCCESS = 'GET_ADDRESSES_SUCCESS';
const GET_ADDRESSES_FAILURE = 'GET_ADDRESSES_FAILURE';

const POST_ADDRESS = 'POST_ADDRESS';
const POST_ADDRESS_REQUEST = 'POST_ADDRESS_REQUEST';
const POST_ADDRESS_SUCCESS = 'POST_ADDRESS_SUCCESS';
const POST_ADDRESS_FAILURE = 'POST_ADDRESS_FAILURE';

export default {
  GET_ADDRESSES,
  GET_ADDRESSES_FAILURE,
  GET_ADDRESSES_REQUEST,
  GET_ADDRESSES_SUCCESS,
  POST_ADDRESS,
  POST_ADDRESS_SUCCESS,
  POST_ADDRESS_FAILURE,
  POST_ADDRESS_REQUEST
};
