const GET_ORDERS = 'GET_ORDERS';
const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE';

const ADD_TO_CART = 'ADD_TO_CART';

const POST_ORDER = 'POST_ORDER';
const POST_ORDER_REQUEST = 'POST_ORDER_REQUEST';
const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';
const POST_ORDER_FAILURE = 'POST_ORDER_FAILURE';

export default {
  GET_ORDERS,
  GET_ORDERS_FAILURE,
  GET_ORDERS_REQUEST,
  GET_ORDERS_SUCCESS,
  ADD_TO_CART,
  POST_ORDER,
  POST_ORDER_FAILURE,
  POST_ORDER_REQUEST,
  POST_ORDER_SUCCESS
};
