const GET_PRODUCTS = 'GET_PRODUCTS';
const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

const GET_PRODUCT = 'GET_PRODUCT';
const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';

const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';
const SET_SORT_FILTER = 'SET_SORT_FILTER';

export default {
  GET_PRODUCT,
  GET_PRODUCTS,
  GET_PRODUCTS_REQUEST,
  GET_PRODUCTS_SUCCESS,
  GET_PRODUCTS_FAILURE,
  GET_PRODUCT_REQUEST,
  GET_PRODUCT_SUCCESS,
  GET_PRODUCT_FAILURE,
  SET_CATEGORY_FILTER,
  SET_SORT_FILTER
};
