const GET_REVIEWS = 'GET_REVIEWS';
const GET_REVIEWS_REQUEST = 'GET_REVIEWS_REQUEST';
const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
const GET_REVIEWS_FAILURE = 'GET_REVIEWS_FAILURE';

const POST_REVIEW = 'POST_REVIEW';
const POST_REVIEW_REQUEST = 'POST_REVIEW_REQUEST';
const POST_REVIEW_SUCCESS = 'POST_REVIEW_SUCCESS';
const POST_REVIEW_FAILURE = 'POST_REVIEW_FAILURE';

export default {
  GET_REVIEWS,
  GET_REVIEWS_FAILURE,
  GET_REVIEWS_REQUEST,
  GET_REVIEWS_SUCCESS,
  POST_REVIEW,
  POST_REVIEW_FAILURE,
  POST_REVIEW_REQUEST,
  POST_REVIEW_SUCCESS
};
