const GET_ORDERS = 'GET_ORDERS';
const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE';

const PATCH_ORDER = 'PATCH_ORDER';
const PATCH_ORDER_REQUEST = 'PATCH_ORDER_REQUEST';
const PATCH_ORDER_SUCCESS = 'PATCH_ORDER_SUCCESS';
const PATCH_ORDER_FAILURE = 'PATCH_ORDER_FAILURE';

export default {
  GET_ORDERS,
  GET_ORDERS_FAILURE,
  GET_ORDERS_REQUEST,
  GET_ORDERS_SUCCESS,
  PATCH_ORDER,
  PATCH_ORDER_FAILURE,
  PATCH_ORDER_REQUEST,
  PATCH_ORDER_SUCCESS
};
